---
- name: Setup development environment configuration
  hosts: dev-env
  remote_user: '{{ remote_user }}'
  roles:
    - pycharm
    - docker_compose
    - inasafe_django
  vars_prompt:
    - name: "ansible_sudo_pass"
      prompt: "Sudo password"
      private: yes
