---
- name: customize django settings file and secret
  template:
    src: '{{ item }}.j2'
    dest: '{{ project_path }}/django_project/core/settings/{{ item }}'
    owner: '{{ remote_user }}'
    group: '{{ remote_group }}'
    mode: "u=rw,g=rw,o=r"
  with_items:
    - custom_settings.py
    - mapquest.py
    - secret.py

- name: customize InaSAFE Realtime celery config
  template:
    src: 'celeryconfig.py.j2'
    dest: '{{ project_path }}/django_project/realtime/tasks/realtime/celeryconfig.py'
    owner: '{{ remote_user }}'
    group: '{{ remote_group }}'
    mode: "u=rw,g=rw,o=r"
